/**
 * 整理页（`/organize`）文案：五个分区（标签 / 收藏夹 / 收藏 / 批注 / 已保存视图）
 * 的标题、说明、空态与回执。分区切换用 `?tab=`，标题同时是页内导航的文案。
 */
export const organize = {
    title: "整理",
    description: "标签、收藏夹、收藏、批注与已保存视图",
    tabs: {
        labels: "标签",
        collections: "收藏夹",
        favorites: "收藏",
        annotations: "批注",
        views: "已保存视图",
    },
    /** 分区标题右侧的条目数；五个分区共用一个外壳，所以后缀只有一份。 */
    sectionCount: (count: number) => `${count} 项`,
    labels: {
        summary: "给内容打的可复用名字；在这里新建与删除，Story 页只能挂已有标签",
        empty: "还没有标签。在内容上打标签要先在这里建一个。",
        newName: "新标签名称",
        create: "新建标签",
        created: (name: string) => `已创建标签「${name}」`,
        createFailed: "创建标签失败",
        removed: (name: string) => `已删除标签「${name}」`,
        removeFailed: "删除标签失败",
        removeLabel: (name: string) => `删除标签 ${name}`,
        readFailed: "读取标签内容失败",
        useCount: (count: number) => `${count} 处`,
        noContent: "没有可显示的内容。",
        emptyOnTargets: "这个标签还没有挂到任何东西上。",
        rename: (name: string) => `重命名标签 ${name}`,
        renameField: "标签新名称",
        renameSubmit: "保存名称",
        renameCancel: "取消重命名",
        renamed: (name: string) => `标签已改名为「${name}」`,
        renameFailed: "标签改名失败",
    },
    collections: {
        summary: "按自己的方式分组的集合；成员在 Story 页勾选，这里可以移出",
        empty: "还没有收藏夹。收藏夹用来把一批内容按你的目的放在一起。",
        newName: "新收藏夹名称",
        create: "新建收藏夹",
        created: (name: string) => `已创建收藏夹「${name}」`,
        createFailed: "创建收藏夹失败",
        removed: (name: string) => `已删除收藏夹「${name}」`,
        removeFailed: "删除收藏夹失败",
        removeLabel: (name: string) => `删除收藏夹 ${name}`,
        readFailed: "读取收藏夹失败",
        itemCount: (count: number) => `${count} 条`,
        emptyMembers: "这个收藏夹还是空的。成员在 Story 页勾选。",
        removeItem: (title: string) => `把 ${title} 移出收藏夹`,
        itemRemoved: (title: string) => `已把「${title}」移出收藏夹`,
        rename: "改名或改描述",
        renameName: "收藏夹名称",
        renameDescription: "收藏夹描述（可留空）",
        renameSubmit: "保存",
        renameCancel: "取消",
        renamed: (name: string) => `已保存收藏夹「${name}」`,
        renameFailed: "保存收藏夹失败",
        itemRemoveFailed: "移出收藏夹失败",
    },
    favorites: {
        summary: "标了星的内容；收藏在 Story 页随手点，这里用来回收",
        empty: "还没有收藏。读一条内容时点「收藏」，它会出现在这里。",
        missingStory: "这条内容已经读不到了",
        favoritedAt: "收藏于",
        remove: "取消收藏",
        removed: "已取消收藏",
        removeFailed: "取消收藏失败",
    },
    annotations: {
        summary: "写给内容、条目或话题的笔记；在对应对象上写，这里用来回顾",
        empty: "还没有批注。读内容时写下的想法会出现在这里。",
        attachedTo: "挂在",
        attachedSuffix: "上",
        targetMissing: "（目标已不可读）",
        removeLabel: "删除这条批注",
        removed: "已删除批注",
        removeFailed: "删除批注失败",
    },
    views: {
        summary: "存下来的一组检索条件；在信息库保存，这里用来查看与删除",
        empty: "还没有视图。在信息库设好筛选条件后点「保存当前条件」。",
        removeLabel: (name: string) => `删除视图 ${name}`,
        removed: (name: string) => `已删除视图「${name}」`,
        removeFailed: "删除视图失败",
        conditionText: (text: string) => `关键词「${text}」`,
        conditionSource: "限定来源",
        conditionFrom: (date: string) => `从 ${date}`,
        conditionTo: (date: string) => `到 ${date}`,
        conditionLabels: (count: number) => `${count} 个标签`,
        conditionTopics: (count: number) => `${count} 个话题`,
        noConditions: "没有条件（等同全部内容）",
    },
} as const;
