/**
 * 包入口：只做导出与模块地图，不放实现。
 * 公共面由 `entry-surface.txt` 冻结、`entry-contract.test.ts` 看守；改导出前先看 `MODULE.md`。
 */

export {
    aiHotSourceConfigSchema, assetErrorCodeSchema, assetErrorCodes, bilibiliSourceConfigSchema,
    connectionInstanceSchema, connectionStatusSchema, contentKindSchema, contentMetricsSchema,
    createConnectionCommandSchema, createSourceCommandSchema, deleteSourceCommandSchema,
    discoveryChannelSchema,
    fixtureRssSourceConfigSchema,
    getSourceConfigurationSchema, idempotencyKeySchema, ingestCommandSchema,
    mediaPolicyCeilings, mediaPolicyImagesSchema, mediaRetryCeiling, mediaRetryPolicySchema,
    protocolVersion, publisherKindSchema, publisherMetricsSchema, publisherSchema,
    retryableAssetErrorCodes, rssSourceConfigSchema, sourceActivationCommandSchema,
    sourceConfigSchema, sourceConfigurationSchemas, sourceConnectorIdSchema,
    sourceDefinitionRefSchema, sourceExecutionSnapshotSchema, sourceKindSchema,
    sourceMediaPolicySchema, sourceOperationIdSchema, sourceProbeResultSchema,
    sourceRevisionIdSchema, sourceSnapshotSchema, sourceTestResultSchema,
    temporalFallbackSchema, temporalPrecisionSchema, temporalValueSchema, triggerBindingSchema,
    triggerConfigSchema, triggerIntervalSchema, triggerKindSchema,
    updateConnectionCommandSchema, updateSourceCommandSchema, type AiHotSourceConfig,
    type AssetErrorCode, type BilibiliSourceConfig, type ConnectionInstance,
    type ConnectionStatus, type ContentKind, type ContentMetrics, type CreateConnectionCommand,
    type CreateSourceCommand, type DeleteSourceCommand, type DiscoveryChannel, type FixtureRssSourceConfig, type IngestCommand,
    type MediaPolicyImages, type MediaRetryPolicy, type Publisher, type PublisherKind,
    type PublisherMetrics, type RssSourceConfig, type SourceActivationCommand,
    type SourceConfig, type SourceConnectorId, type SourceDefinitionRef,
    type SourceExecutionSnapshot, type SourceKind, type SourceMediaPolicy,
    type SourceOperationId, type SourceProbeResult, type SourceRevisionId, type SourceSnapshot,
    type SourceTestResult, type TemporalFallback, type TemporalPrecision, type TemporalValue,
    type TriggerBinding, type TriggerConfig, type TriggerKind, type UpdateConnectionCommand,
    type UpdateSourceCommand,
} from "./base.js";

export {
    assetSnapshotSchema, assetStatusSchema, connectorDescriptorSchema, ingestResultSchema,
    jobKindSchema, jobListSchema, jobSnapshotSchema, jobStatusSchema, jsonSchemaRefSchema, manifestHashSchema,
    mediaCleanupCommandSchema, mediaCleanupEntrySchema, mediaCleanupReportSchema,
    mediaCleanupRunSnapshotSchema, publicAssetSnapshotSchema, sourceAuthSchema,
    sourceConfigProbeCommandSchema,
    sourceConfigProbeJobPayloadSchema, sourceConfigProbeJobSnapshotSchema,
    sourceConfigProbeResultSchema, sourceDefinitionManifestSchema, sourceDefinitionPageSchema,
    sourceDefinitionStatusSchema, sourceOperationManifestSchema, stepStatusSchema,
    type AssetSnapshot, type AssetStatus, type ConnectorDescriptor, type IngestResult,
    type JobKind, type JobSnapshot, type JobStatus, type JsonSchemaRef, type ManifestHash,
    type MediaCleanupCommand, type MediaCleanupEntry, type MediaCleanupReport,
    type MediaCleanupRunSnapshot, type PublicAssetSnapshot, type SourceAuth,
    type SourceConfigProbeCommand,
    type SourceConfigProbeJobSnapshot, type SourceConfigProbeResult,
    type SourceDefinitionManifest, type SourceDefinitionPage, type SourceDefinitionStatus,
    type SourceOperationManifest, type StepStatus,
} from "./source.js";
export {
    cancelRunCommandSchema, recoverRunCommandSchema, rerunRunCommandSchema,
    runControlActionSchema, runControlResultSchema, runSnapshotSchema, runStatusSchema,
    type CancelRunCommand, type RecoverRunCommand, type RerunRunCommand, type RunControlAction,
    type RunControlResult, type RunSnapshot, type RunStatus,
} from "./run-control.js";
export {
    backupSnapshotSchema, eventSnapshotSchema, healthResponseSchema, serviceErrorCodeSchema,
    serviceErrorSchema, snapshotRequiredPayloadSchema, sseEventSchema, storageStatsSchema,
    type BackupSnapshot, type EventEnvelope, type EventSnapshot, type HealthResponse,
    type ServiceError, type ServiceErrorCode, type SnapshotRequiredPayload, type SseEvent,
    type StorageStats,
} from "./platform.js";
export {
    feedItemSchema, feedPageSchema, searchPageSchema, searchQuerySchema, searchResultSchema,
    type FeedItem, type FeedPage, type SearchPage, type SearchQuery, type SearchResult,
} from "./search.js";
export {
    entryDetailSchema, entryListItemSchema, entryListQuerySchema, entryPageSchema,
    entryRelatedStorySchema, entryRelationProvenanceSchema, entryRelationSchema,
    entryRelationTypeSchema, entryRevisionSnapshotSchema, entryStoryLinkProvenanceSchema,
    entryStoryRelationTypeSchema, linkEntryRelationCommandSchema, observationSnapshotSchema,
    revisionDetailSchema, storyEvidenceSchema, unlinkEntryRelationCommandSchema,
    type EntryDetail, type EntryListItem, type EntryListQuery,
    type EntryPage, type EntryRelatedStory, type EntryRelation,
    type EntryRelationProvenance, type EntryRelationType, type EntryRevisionSnapshot,
    type EntryStoryLinkProvenance, type EntryStoryRelationType,
    type LinkEntryRelationCommand, type ObservationSnapshot,
    type RevisionDetail, type StoryEvidence, type UnlinkEntryRelationCommand,
} from "./entry-relation.js";
export {
    labelRefSchema, linkEntryStoryCommandSchema, mergeStoriesCommandSchema,
    migrateStoryUserStateCommandSchema, moveEntryToStoryCommandSchema, splitStoryCommandSchema,
    storyDetailSchema, storyEntitySummarySchema, storyKeyFactSchema, storySplitSuccessorSchema,
    storySuccessorSchema, storyTimeRangeSchema, storyTopicSchema,
    storyUserStateMigrationCountsSchema,
    storyUserStateMigrationResultSchema, unlinkEntryStoryCommandSchema,
    updateStoryRevisionCommandSchema,
    type LabelRef, type LinkEntryStoryCommand, type MergeStoriesCommand,
    type MigrateStoryUserStateCommand, type MoveEntryToStoryCommand, type SplitStoryCommand,
    type StoryDetail, type StoryEntitySummary, type StoryKeyFact, type StorySplitSuccessor,
    type StorySuccessor, type StoryTimeRange,
    type StoryTopic, type StoryUserStateMigrationCounts, type StoryUserStateMigrationResult,
    type UnlinkEntryStoryCommand, type UpdateStoryRevisionCommand,
} from "./story.js";
export {
    storySubtypePageSchema, storySubtypeQuerySchema, storySubtypeSchema,
    storySubtypeStatusSchema, type StorySubtype, type StorySubtypePage, type StorySubtypeQuery,
    type StorySubtypeStatus,
} from "./story-subtype.js";
export {
    addTopicMemberCommandSchema, createTopicCommandSchema, mergeTopicsCommandSchema,
    removeTopicMemberCommandSchema, restoreTopicMemberCommandSchema, topicDetailSchema,
    topicMemberRoleSchema, topicMemberSchema, topicPageSchema, topicSummarySchema,
    updateTopicCommandSchema, updateTopicMemberRoleCommandSchema, type AddTopicMemberCommand,
    type CreateTopicCommand, type MergeTopicsCommand, type RemoveTopicMemberCommand,
    type RestoreTopicMemberCommand, type TopicDetail, type TopicMember, type TopicMemberRole,
    type TopicPage, type TopicSummary, type UpdateTopicCommand,
    type UpdateTopicMemberRoleCommand,
} from "./topic.js";
export {
    addEntityAliasCommandSchema, createEntityCommandSchema, createEntityRelationCommandSchema,
    entityDetailSchema, entityLinkProvenanceSchema, entityPageSchema, entityRelationSchema,
    entityRelationTypeSchema, entitySchema, entityStoryLinkSchema, entitySummarySchema,
    entityTypeSchema, linkStoryEntityCommandSchema, removeEntityAliasCommandSchema,
    removeEntityRelationCommandSchema, unlinkStoryEntityCommandSchema,
    updateEntityCommandSchema, type AddEntityAliasCommand, type CreateEntityCommand,
    type CreateEntityRelationCommand, type Entity, type EntityDetail,
    type EntityLinkProvenance, type EntityPage, type EntityRelation, type EntityRelationType,
    type EntityStoryLink, type EntitySummary, type EntityType, type LinkStoryEntityCommand,
    type RemoveEntityAliasCommand, type RemoveEntityRelationCommand,
    type UnlinkStoryEntityCommand, type UpdateEntityCommand,
} from "./entity.js";
export {
    annotationListSchema, annotationSchema, annotationTargetQuerySchema,
    collectionDetailSchema, collectionItemCommandSchema, collectionListSchema,
    collectionSummarySchema, createAnnotationCommandSchema, createCollectionCommandSchema,
    createLabelCommandSchema, createSavedViewCommandSchema, favoriteCommandSchema,
    favoriteItemSchema, favoriteListSchema, favoriteTargetTypeSchema,
    labelAssignmentCommandSchema, labelDetailSchema, labelItemSchema, labelListSchema,
    savedViewConditionsSchema, savedViewListSchema, savedViewSchema, targetTypeSchema,
    updateAnnotationCommandSchema, updateCollectionCommandSchema, updateSavedViewCommandSchema,
    userOrganizationAckSchema, type Annotation, type AnnotationList,
    type AnnotationTargetQuery, type CollectionDetail, type CollectionItemCommand,
    type CollectionList, type CollectionSummary, type CreateAnnotationCommand,
    type CreateCollectionCommand, type CreateLabelCommand, type CreateSavedViewCommand,
    type FavoriteCommand, type FavoriteItem, type FavoriteList, type FavoriteTargetType,
    type LabelAssignmentCommand, type LabelDetail, type LabelItem, type LabelList,
    type SavedView, type SavedViewConditions, type SavedViewList, type TargetType,
    type UpdateAnnotationCommand, type UpdateCollectionCommand, type UpdateSavedViewCommand,
    type UserOrganizationAck,
} from "./user-organization.js";
export {
    blockConfigSchemaFor, blockConfigSchemas, blockTypeSchema, boardBlockSchema,
    boardCommandAckSchema, boardDetailSchema, boardListSchema, boardSectionSchema,
    boardSummarySchema, createBlockCommandSchema, createBoardCommandSchema,
    createSectionCommandSchema, moveBlockCommandSchema, pinSpotlightCommandSchema,
    setBlockVisibilityCommandSchema, spotlightPlacementListSchema, spotlightPlacementSchema,
    spotlightTargetTypeSchema, updateBlockConfigCommandSchema, updateBoardCommandSchema,
    updateSectionCommandSchema, type BlockType, type BoardBlock, type BoardCommandAck,
    type BoardDetail, type BoardList, type BoardSection, type BoardSummary,
    type CollectionBlockConfig, type CreateBlockCommand, type CreateBoardCommand,
    type CreateSectionCommand, type FeedBlockConfig, type MoveBlockCommand,
    type PinSpotlightCommand, type SetBlockVisibilityCommand, type SourceHealthBlockConfig,
    type SpotlightBlockConfig, type SpotlightPlacement, type SpotlightPlacementList,
    type TopicListBlockConfig, type UpdateBlockConfigCommand, type UpdateBoardCommand,
    type UpdateSectionCommand,
} from "./board.js";

export {
    actionDefinitionSchema, actionDescriptorSchema, actionErrorCodeSchema,
    actionExecutionSchema, actionKindSchema, actionManifestSchema, actionRefSchema,
    blobRefSchema, executionPlacementSchema, ingestTriggerKindSchema, libraryIngestInputSchema,
    libraryIngestOutputSchema, mediaRetryApplyInputSchema, mediaRetryApplyOutputSchema,
    mediaRetryFetchInputSchema, mediaRetryFetchOutputSchema, mediaRetryOutcomeSchema,
    mediaRetryPolicySnapshotSchema, normalizedAssetInputSchema, normalizedIngestItemSchema,
    parseActionRef, retryPolicySchema, sourceCheckpointInputSchema,
    sourceCheckpointOutputSchema, sourceFetchInputSchema, sourceFetchOutputSchema,
    type ActionDefinition, type ActionDescriptor, type ActionErrorCode, type ActionExecution,
    type ActionKind, type ActionManifest, type ActionRef, type BlobRef,
    type ExecutionPlacement, type IngestTriggerKind, type JsonValue, type LibraryIngestInput,
    type LibraryIngestOutput, type MediaRetryApplyInput, type MediaRetryApplyOutput,
    type MediaRetryFetchInput, type MediaRetryFetchOutput, type MediaRetryOutcomeContract,
    type MediaRetryPolicySnapshot, type NormalizedAssetInputContract,
    type NormalizedIngestItemContract, type ParsedActionRef, type RetryPolicy,
    type SourceCheckpointInput, type SourceCheckpointOutput, type SourceFetchInput,
    type SourceFetchOutput,
} from "./action.js";
