import {renderSystemOutput, systemOutputControls} from "../primitive-fixtures";
import {
    renderBoardBlockListLab,
    renderBoardViewLab,
    renderCollectionPlanListLab,
    renderConnectionPanelLab,
    renderEntityPanelLab,
    renderFeedBrowserLab,
    renderRunControlLab,
    renderRunHistoryLab,
    renderSourceFormLab,
    renderStatusSummaryLab,
    renderStoragePanelLab,
    renderStoryEditPanelLab,
    renderStoryReadingContentLab,
    renderThemeSwitcherLab,
    renderTopicPanelLab,
} from "../product-fixtures";
import type {LabComponentDefinition, LabControlDefinition} from "../types";
import {
    collectionPlanListControls,
    connectionPanelControls,
    entityPanelControls,
    feedBrowserControls,
    runControlControls,
    runHistoryControls,
    sourceFormControls,
    statusSummaryControls,
    storyPanelControls,
    topicPanelControls,
} from "./controls";
import {control, sharedTokens} from "./shared";

/** components/cosmos 顶层产品组件的登记表。 */
export const cosmosComponentDefinitions = [
    {
        id: "feed-browser",
        label: "FeedBrowser",
        category: "Cosmos",
        modulePath: "components/cosmos/feed-browser.tsx",
        defaultSceneId: "populated",
        controls: feedBrowserControls,
        scenes: [
            {id: "populated", label: "Populated", props: {title: "Cosmos fixture story", state: "populated"}},
            {id: "loading", label: "Loading", props: {title: "Cosmos fixture story", state: "loading"}},
            {id: "empty", label: "Empty", props: {title: "Cosmos fixture story", state: "empty"}},
        ],
        tokens: sharedTokens,
        render: renderFeedBrowserLab,
    },
    {
        id: "collection-plan-list",
        label: "CollectionPlanList",
        category: "Cosmos",
        modulePath: "components/cosmos/collection-plan-list.tsx",
        defaultSceneId: "configured",
        controls: collectionPlanListControls,
        scenes: [
            {id: "configured", label: "Configured", props: {sourceName: "Cosmos fixture", state: "configured", enabled: true, grouped: false}},
            {id: "grouped", label: "Grouped by connection", props: {sourceName: "Cosmos fixture", state: "configured", enabled: true, grouped: true}},
            {id: "untimed", label: "Untimed", props: {sourceName: "Cosmos fixture", state: "untimed", enabled: true, grouped: false}},
            {id: "empty", label: "Empty", props: {sourceName: "Cosmos fixture", state: "empty", enabled: true, grouped: false}},
            {id: "disabled", label: "Disabled", props: {sourceName: "Cosmos fixture", state: "disabled", enabled: false, grouped: false}},
            {id: "media-policy", label: "Media policy tightened", props: {sourceName: "Cosmos fixture", state: "media-policy", enabled: true, grouped: false}},
        ],
        tokens: sharedTokens,
        render: renderCollectionPlanListLab,
    },
    {
        id: "run-control",
        label: "RunControl",
        category: "Cosmos",
        modulePath: "components/cosmos/run-control.tsx",
        defaultSceneId: "failed",
        controls: runControlControls,
        scenes: [
            {id: "queued", label: "Queued", props: {status: "queued"}},
            {id: "running", label: "Running", props: {status: "running"}},
            {id: "succeeded", label: "Succeeded", props: {status: "succeeded"}},
            {id: "failed", label: "Failed", props: {status: "failed"}},
            {id: "cancelled", label: "Cancelled", props: {status: "cancelled"}},
        ],
        tokens: sharedTokens,
        render: renderRunControlLab,
    },
    {
        id: "run-history",
        label: "RunHistory",
        category: "Cosmos",
        modulePath: "components/cosmos/run-history.tsx",
        defaultSceneId: "populated",
        controls: runHistoryControls,
        scenes: [
            {id: "populated", label: "Populated", props: {state: "populated"}},
            {id: "empty", label: "Empty", props: {state: "empty"}},
        ],
        tokens: sharedTokens,
        render: renderRunHistoryLab,
    },
    {
        id: "connection-panel",
        label: "ConnectionPanel",
        category: "Cosmos",
        modulePath: "components/cosmos/connection-panel.tsx",
        defaultSceneId: "populated",
        controls: connectionPanelControls,
        scenes: [
            {id: "populated", label: "Populated", props: {state: "populated"}},
            {id: "empty", label: "Empty", props: {state: "empty"}},
        ],
        tokens: sharedTokens,
        render: renderConnectionPanelLab,
    },
    {
        id: "storage-panel",
        label: "StoragePanel",
        category: "Cosmos",
        modulePath: "components/cosmos/storage-panel.tsx",
        defaultSceneId: "default",
        controls: [],
        scenes: [
            {id: "default", label: "Default", props: {}},
        ],
        tokens: sharedTokens,
        render: renderStoragePanelLab,
    },
    {
        id: "source-form",
        label: "SourceForm",
        category: "Cosmos",
        modulePath: "components/cosmos/source-form.tsx",
        defaultSceneId: "default",
        controls: sourceFormControls,
        scenes: [
            {id: "default", label: "Default", props: {name: "Cosmos RSS", feedUrl: "https://example.com/feed.xml", definitionState: "ready", probeState: "idle"}},
            {id: "long-text", label: "Long text", props: {name: "A source name long enough to test wrapping", feedUrl: "https://example.com/a-very-long-feed-url.xml", definitionState: "ready", probeState: "idle"}},
            {id: "probe-success", label: "Probe success", props: {name: "Cosmos RSS", feedUrl: "https://example.com/feed.xml", definitionState: "ready", probeState: "succeeded"}},
            {id: "definition-error", label: "Definition error", props: {name: "Cosmos RSS", feedUrl: "https://example.com/feed.xml", definitionState: "error", probeState: "idle"}},
        ],
        tokens: sharedTokens,
        render: renderSourceFormLab,
    },
    {
        id: "status-summary",
        label: "StatusSummary",
        category: "Cosmos",
        modulePath: "components/cosmos/status-summary.tsx",
        defaultSceneId: "default",
        controls: statusSummaryControls,
        scenes: [
            {id: "default", label: "Default", props: {sourceSummary: "2 个来源，1 个启用", health: "ready", eventStreamState: "connected"}},
            {id: "unavailable", label: "Unavailable", props: {sourceSummary: "尚未配置来源", health: "unknown", eventStreamState: "unavailable"}},
            {id: "failed", label: "Failed", props: {sourceSummary: "1 个来源，0 个启用", health: "failed", eventStreamState: "connecting"}},
        ],
        tokens: sharedTokens,
        render: renderStatusSummaryLab,
    },
    {
        id: "story-reading-content",
        label: "StoryReadingContent",
        category: "Cosmos",
        modulePath: "components/cosmos/story-reading-content.tsx",
        defaultSceneId: "representation",
        controls: storyPanelControls,
        scenes: [
            {id: "default", label: "Default", props: {title: "Cosmos fixture story", contentText: "A synthetic Story body for component inspection.", state: "revision"}},
            {id: "empty", label: "Empty revision", props: {title: "Story without revision", contentText: "", state: "empty"}},
            {id: "representation", label: "Time range and key facts", props: {title: "Cosmos fixture story", contentText: "The laboratory renders the event time line and the key facts block from the fixture values.", state: "representation"}},
            {id: "human-protected", label: "Human-edited representation", props: {title: "Cosmos fixture story", contentText: "The laboratory renders the notice that automatic updates stopped because a human wrote the current revision.", state: "human-protected"}},
            {id: "entry-relations", label: "Duplicate and syndication", props: {title: "Cosmos fixture story", contentText: "The laboratory renders the member-row relation annotation and its mark/remove controls.", state: "entry-relations"}},
            {id: "split-shell", label: "Historical shell", props: {title: "Cosmos fixture story", contentText: "", state: "split"}},
        ],
        tokens: sharedTokens,
        render: renderStoryReadingContentLab,
    },
    {
        id: "story-edit-panel",
        label: "StoryEditPanel",
        category: "Cosmos",
        modulePath: "components/cosmos/story-edit-panel.tsx",
        defaultSceneId: "splittable",
        controls: storyPanelControls,
        scenes: [
            {id: "default", label: "Default", props: {title: "Cosmos fixture story", contentText: "A synthetic Story body for component inspection.", state: "representation"}},
            {id: "splittable", label: "Splittable (two members)", props: {title: "Cosmos fixture story", contentText: "Two members let the laboratory exercise the split form.", state: "splittable"}},
            {id: "split-shell", label: "Historical shell", props: {title: "Cosmos fixture story", contentText: "", state: "split"}},
            {id: "legacy-subtype", label: "Legacy subtype", props: {title: "Story with an unregistered subtype", contentText: "", state: "legacy-subtype"}},
        ],
        tokens: sharedTokens,
        render: renderStoryEditPanelLab,
    },
    {
        id: "topic-panel",
        label: "TopicPanel",
        category: "Cosmos",
        modulePath: "components/cosmos/topic-panel.tsx",
        defaultSceneId: "members",
        controls: topicPanelControls,
        scenes: [
            {id: "members", label: "Members", props: {title: "Cosmos fixture topic", state: "members"}},
            {id: "empty", label: "Empty", props: {title: "Cosmos fixture topic", state: "empty"}},
            {id: "removed", label: "Removed", props: {title: "Cosmos fixture topic", state: "removed"}},
        ],
        tokens: sharedTokens,
        render: renderTopicPanelLab,
    },
    {
        id: "entity-panel",
        label: "EntityPanel",
        category: "Cosmos",
        modulePath: "components/cosmos/entity-panel.tsx",
        defaultSceneId: "linked",
        controls: entityPanelControls,
        scenes: [
            {id: "linked", label: "Linked", props: {name: "Jeff Dean", type: "person", state: "linked"}},
            {id: "empty", label: "Empty", props: {name: "Jeff Dean", type: "person", state: "empty"}},
        ],
        tokens: sharedTokens,
        render: renderEntityPanelLab,
    },
    {
        id: "board-view",
        label: "BoardView",
        category: "Cosmos",
        modulePath: "components/cosmos/board-view.tsx",
        defaultSceneId: "default",
        controls: [
            control("state", "State", "select", "default", ["default", "unknown-block"]),
        ] as const satisfies readonly LabControlDefinition[],
        scenes: [
            {id: "default", label: "Default", props: {state: "default"}},
            {id: "unknown-block", label: "Unknown block", props: {state: "unknown-block"}},
        ],
        tokens: sharedTokens,
        render: renderBoardViewLab,
    },
    {
        id: "board-sortable-blocks",
        label: "BoardBlockList",
        category: "Cosmos",
        modulePath: "components/cosmos/board-sortable-blocks.tsx",
        defaultSceneId: "default",
        controls: [
            control("state", "State", "select", "default", ["default", "unknown-block"]),
        ] as const satisfies readonly LabControlDefinition[],
        scenes: [
            {id: "default", label: "Default", props: {state: "default"}},
            {id: "unknown-block", label: "Unknown block", props: {state: "unknown-block"}},
        ],
        tokens: sharedTokens,
        render: renderBoardBlockListLab,
    },
    {
        id: "theme-switcher",
        label: "ThemeSwitcher",
        category: "Cosmos",
        modulePath: "components/cosmos/theme-switcher.tsx",
        defaultSceneId: "default",
        controls: [
            control("value", "Value", "select", "system", ["system", "light", "dark"]),
        ] as const satisfies readonly LabControlDefinition[],
        scenes: [
            {id: "default", label: "System", props: {value: "system"}},
            {id: "light", label: "Light", props: {value: "light"}},
            {id: "dark", label: "Dark", props: {value: "dark"}},
        ],
        tokens: sharedTokens,
        render: renderThemeSwitcherLab,
    },
    {
        id: "system-output-block",
        label: "SystemOutputBlock",
        category: "Cosmos",
        modulePath: "components/cosmos/system-output-block.tsx",
        defaultSceneId: "machine",
        controls: systemOutputControls,
        scenes: [
            {id: "machine", label: "Machine only", props: {state: "machine"}},
            {id: "mixed", label: "Mixed with human", props: {state: "mixed"}},
            {id: "empty", label: "Empty", props: {state: "empty"}},
        ],
        tokens: sharedTokens,
        render: renderSystemOutput,
    },
] as const satisfies readonly LabComponentDefinition[];
