import {
    alertDialogControls,
    comboboxControls,
    dialogControls,
    menuControls,
    renderAlertDialog,
    renderCombobox,
    renderDialog,
    renderMenu,
    renderSelect,
    renderTabs,
    renderToast,
    renderTooltip,
    selectControls,
    tabsControls,
    toastControls,
    tooltipControls,
} from "../primitive-fixtures";
import type {LabComponentDefinition} from "../types";
import {
    badgeControls,
    buttonControls,
    cardControls,
    fieldControls,
    inputControls,
    labelControls,
    separatorControls,
    textareaControls,
} from "./controls";
import {sharedTokens} from "./shared";
import {
    renderBadge,
    renderButton,
    renderCard,
    renderField,
    renderInput,
    renderLabel,
    renderSeparator,
    renderTextarea,
} from "./ui-renderers";

/** components/ui 顶层 primitive 的登记表（含切片 2 新增的 8 个）。 */
export const uiComponentDefinitions = [
    {
        id: "badge",
        label: "Badge",
        category: "Display",
        modulePath: "components/ui/badge.tsx",
        defaultSceneId: "default",
        controls: badgeControls,
        scenes: [
            {id: "default", label: "Default", props: {label: "Badge", variant: "default"}},
            {id: "status", label: "Status", props: {label: "Ready", variant: "secondary"}},
            {id: "danger", label: "Danger", props: {label: "Failed", variant: "destructive"}},
        ],
        tokens: sharedTokens,
        render: renderBadge,
    },
    {
        id: "button",
        label: "Button",
        category: "Controls",
        modulePath: "components/ui/button.tsx",
        defaultSceneId: "default",
        controls: buttonControls,
        scenes: [
            {id: "default", label: "Default", props: {label: "Continue", variant: "default", size: "default", disabled: false}},
            {id: "destructive", label: "Destructive", props: {label: "Delete", variant: "destructive", size: "default", disabled: false}},
            {id: "disabled", label: "Disabled", props: {label: "Unavailable", variant: "default", size: "default", disabled: true}},
        ],
        tokens: sharedTokens,
        render: renderButton,
    },
    {
        id: "card",
        label: "Card",
        category: "Layout",
        modulePath: "components/ui/card.tsx",
        defaultSceneId: "default",
        controls: cardControls,
        scenes: [
            {id: "default", label: "Default", props: {title: "Card title", description: "Card description", size: "default"}},
            {id: "long-content", label: "Long content", props: {title: "A deliberately long card title that tests wrapping", description: "A longer description lets the laboratory expose hierarchy, wrapping, and panel width without a network fixture.", size: "default"}},
            {id: "compact", label: "Compact", props: {title: "Compact card", description: "Small card spacing", size: "sm"}},
        ],
        tokens: sharedTokens,
        render: renderCard,
    },
    {
        id: "field",
        label: "Field",
        category: "Forms",
        modulePath: "components/ui/field.tsx",
        defaultSceneId: "default",
        controls: fieldControls,
        scenes: [
            {id: "default", label: "Default", props: {label: "Name", placeholder: "Your name", value: "Cosmos", invalid: false, disabled: false}},
            {id: "invalid", label: "Invalid", props: {label: "Email", placeholder: "name@example.com", value: "invalid", invalid: true, disabled: false}},
            {id: "disabled", label: "Disabled", props: {label: "Locked field", placeholder: "Unavailable", value: "Read only", invalid: false, disabled: true}},
        ],
        tokens: sharedTokens,
        render: renderField,
    },
    {
        id: "input",
        label: "Input",
        category: "Forms",
        modulePath: "components/ui/input.tsx",
        defaultSceneId: "default",
        controls: inputControls,
        scenes: [
            {id: "default", label: "Default", props: {placeholder: "Search", value: "", invalid: false, disabled: false}},
            {id: "invalid", label: "Invalid", props: {placeholder: "Search", value: "Bad query", invalid: true, disabled: false}},
            {id: "disabled", label: "Disabled", props: {placeholder: "Unavailable", value: "", invalid: false, disabled: true}},
        ],
        tokens: sharedTokens,
        render: renderInput,
    },
    {
        id: "label",
        label: "Label",
        category: "Forms",
        modulePath: "components/ui/label.tsx",
        defaultSceneId: "default",
        controls: labelControls,
        scenes: [
            {id: "default", label: "Default", props: {label: "Field label"}},
            {id: "long-text", label: "Long text", props: {label: "A label with enough text to test wrapping and readable spacing"}},
        ],
        tokens: sharedTokens,
        render: renderLabel,
    },
    {
        id: "separator",
        label: "Separator",
        category: "Layout",
        modulePath: "components/ui/separator.tsx",
        defaultSceneId: "default",
        controls: separatorControls,
        scenes: [
            {id: "default", label: "Horizontal", props: {orientation: "horizontal"}},
            {id: "vertical", label: "Vertical", props: {orientation: "vertical"}},
        ],
        tokens: sharedTokens,
        render: renderSeparator,
    },
    {
        id: "textarea",
        label: "Textarea",
        category: "Forms",
        modulePath: "components/ui/textarea.tsx",
        defaultSceneId: "default",
        controls: textareaControls,
        scenes: [
            {id: "default", label: "Default", props: {placeholder: "Write a note", value: "Preview text", invalid: false, disabled: false}},
            {id: "long-text", label: "Long text", props: {placeholder: "Write a note", value: "A long multiline value helps verify wrapping and the fixed control boundary in narrow viewports.", invalid: false, disabled: false}},
            {id: "invalid", label: "Invalid", props: {placeholder: "Required", value: "", invalid: true, disabled: false}},
        ],
        tokens: sharedTokens,
        render: renderTextarea,
    },
    {
        id: "dialog",
        label: "Dialog",
        category: "Overlay",
        modulePath: "components/ui/dialog.tsx",
        defaultSceneId: "closed",
        controls: dialogControls,
        scenes: [
            {id: "closed", label: "Closed", props: {open: false, title: "归并到已有 Story", description: "两条内容会合并成一条，原来的记录仍然保留在历史里。"}},
            {id: "open", label: "Open", props: {open: true, title: "归并到已有 Story", description: "两条内容会合并成一条，原来的记录仍然保留在历史里。"}},
            {id: "long-copy", label: "Long copy", props: {open: true, title: "把一个话题的成员迁移到另一个话题", description: "迁移只改变成员归类，不改写任何内容的正文；已经被人工确认过的成员会保留可恢复的历史记录，因此这一步可以回退。"}},
        ],
        tokens: sharedTokens,
        render: renderDialog,
    },
    {
        id: "alert-dialog",
        label: "AlertDialog",
        category: "Overlay",
        modulePath: "components/ui/alert-dialog.tsx",
        defaultSceneId: "closed",
        controls: alertDialogControls,
        scenes: [
            {id: "closed", label: "Closed", props: {open: false, danger: true, title: "删除这个标签？", description: "删除后，这个标签下挂着的 Story 仍然保留，只是不再带这个标签。"}},
            {id: "destructive", label: "Destructive", props: {open: true, danger: true, title: "删除这个标签？", description: "删除后，这个标签下挂着的 Story 仍然保留，只是不再带这个标签。"}},
            {id: "reversible", label: "Reversible", props: {open: true, danger: false, title: "把这条移出话题？", description: "移出后可以随时恢复，角色与纳入理由都会保留。"}},
        ],
        tokens: sharedTokens,
        render: renderAlertDialog,
    },
    {
        id: "menu",
        label: "Menu",
        category: "Overlay",
        modulePath: "components/ui/menu.tsx",
        defaultSceneId: "closed",
        controls: menuControls,
        scenes: [
            {id: "closed", label: "Closed", props: {open: false, disabledItem: false}},
            {id: "open", label: "Open", props: {open: true, disabledItem: false}},
            {id: "with-disabled", label: "With disabled item", props: {open: true, disabledItem: true}},
        ],
        tokens: sharedTokens,
        render: renderMenu,
    },
    {
        id: "tabs",
        label: "Tabs",
        category: "Navigation",
        modulePath: "components/ui/tabs.tsx",
        defaultSceneId: "default",
        controls: tabsControls,
        scenes: [
            {id: "default", label: "Labels", props: {selected: "labels"}},
            {id: "collections", label: "Collections", props: {selected: "collections"}},
            {id: "favorites", label: "Favorites", props: {selected: "favorites"}},
        ],
        tokens: sharedTokens,
        render: renderTabs,
    },
    {
        id: "toast",
        label: "Toast",
        category: "Feedback",
        modulePath: "components/ui/toast.tsx",
        defaultSceneId: "success",
        controls: toastControls,
        scenes: [
            {id: "success", label: "Success", props: {open: true, variant: "success", title: "已收藏", description: "可以在信息库顶部的筛选里找到收藏过的内容。", closable: true}},
            {id: "error", label: "Error", props: {open: true, variant: "error", title: "保存失败", description: "写入没有生效，原文没有被改动。可以重试，或先检查服务是否在运行。", closable: true}},
            {id: "info", label: "Info", props: {open: true, variant: "info", title: "正在重新读取", description: "检测到有新变化，正在后台刷新列表。", closable: false}},
        ],
        tokens: sharedTokens,
        render: renderToast,
    },
    {
        id: "select",
        label: "Select",
        category: "Forms",
        modulePath: "components/ui/select.tsx",
        defaultSceneId: "closed",
        controls: selectControls,
        scenes: [
            {id: "closed", label: "Closed", props: {open: false, value: "saved", disabled: false}},
            {id: "open", label: "Open", props: {open: true, value: "saved", disabled: false}},
            {id: "disabled", label: "Disabled", props: {open: false, value: "metadata_only", disabled: true}},
        ],
        tokens: sharedTokens,
        render: renderSelect,
    },
    {
        id: "combobox",
        label: "Combobox",
        category: "Forms",
        modulePath: "components/ui/combobox.tsx",
        defaultSceneId: "closed",
        controls: comboboxControls,
        scenes: [
            {id: "closed", label: "Closed", props: {open: false, query: "", disabled: false}},
            {id: "open", label: "Open", props: {open: true, query: "", disabled: false}},
            {id: "filtered", label: "Filtered", props: {open: true, query: "定价", disabled: false}},
            {id: "no-match", label: "No match", props: {open: true, query: "不存在的话题", disabled: false}},
        ],
        tokens: sharedTokens,
        render: renderCombobox,
    },
    {
        id: "tooltip",
        label: "Tooltip",
        category: "Overlay",
        modulePath: "components/ui/tooltip.tsx",
        defaultSceneId: "closed",
        controls: tooltipControls,
        scenes: [
            {id: "closed", label: "Closed", props: {open: false, text: "依据 3 条 · 置信度 0.72"}},
            {id: "open", label: "Open", props: {open: true, text: "依据 3 条 · 置信度 0.72"}},
            {id: "producer", label: "Producer", props: {open: true, text: "这条内容由你手动编辑过，自动分析不会再覆盖它。"}},
        ],
        tokens: sharedTokens,
        render: renderTooltip,
    },
] as const satisfies readonly LabComponentDefinition[];
